services:
  hcp-client-telegram:
    build: .

    container_name: hcp-client-telegram

    working_dir: /app

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./data:/app/data

    command: python main.py

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
